// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: comcount.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ProtoMsg {

  /// <summary>Holder for reflection information generated from comcount.proto</summary>
  public static partial class ComcountReflection {

    #region Descriptor
    /// <summary>File descriptor for comcount.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ComcountReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5jb21jb3VudC5wcm90bxIIcHJvdG9Nc2caCmdvZ28ucHJvdG8i9wIKCkNv",
            "bUNvdW50TUQSKwoCSUQYASABKARCH/LeHxtnb3JtOiJwcmltYXJ5a2V5O2Nv",
            "bHVtbjppZCISKAoDUElEGAIgASgEQhvy3h8XZ29ybToiaW5kZXg7Y29sdW1u",
            "OnBpZCISLAoIQWRkQ291bnQYCyABKAVCGvLeHxZnb3JtOiJjb2x1bW46YWRk",
            "Y291bnQiEjIKC1JlbWFpbkNvdW50GAwgASgFQh3y3h8ZZ29ybToiY29sdW1u",
            "OnJlbWFpbmNvdW50IhI6Cg9MYXN0UmVmcmVzaFRpbWUYDSABKANCIfLeHx1n",
            "b3JtOiJjb2x1bW46bGFzdHJlZnJlc2h0aW1lIhIqCgdFbmRUaW1lGA4gASgD",
            "Qhny3h8VZ29ybToiY29sdW1uOmVuZHRpbWUiEigKBkJhc2VJZBgPIAEoBUIY",
            "8t4fFGdvcm06ImNvbHVtbjpiYXNlaWQiOh7Koh8IY29tY291bnTwoh8A0KIf",
            "AeCiHwHaoh8CSUQiIwoRVXBDb21Db3VudEluZm9TcnYSDgoGQmFzZUlkGAEg",
            "ASgFQgTI4x4BYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Gogoproto.GogoReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::ProtoMsg.ComCountMD), global::ProtoMsg.ComCountMD.Parser, new[]{ "ID", "PID", "AddCount", "RemainCount", "LastRefreshTime", "EndTime", "BaseId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ProtoMsg.UpComCountInfoSrv), global::ProtoMsg.UpComCountInfoSrv.Parser, new[]{ "BaseId" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  ///---------------------------------------------------------------
  /// 数据表 MD
  /// StartId=5600
  /// 通用计数表结构
  /// </summary>
  public sealed partial class ComCountMD : pb::IMessage<ComCountMD>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ComCountMD> _parser = new pb::MessageParser<ComCountMD>(() => new ComCountMD());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ComCountMD> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ProtoMsg.ComcountReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ComCountMD() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ComCountMD(ComCountMD other) : this() {
      iD_ = other.iD_;
      pID_ = other.pID_;
      addCount_ = other.addCount_;
      remainCount_ = other.remainCount_;
      lastRefreshTime_ = other.lastRefreshTime_;
      endTime_ = other.endTime_;
      baseId_ = other.baseId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ComCountMD Clone() {
      return new ComCountMD(this);
    }

    /// <summary>Field number for the "ID" field.</summary>
    public const int IDFieldNumber = 1;
    private ulong iD_;
    /// <summary>
    ///唯一ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong ID {
      get { return iD_; }
      set {
        iD_ = value;
      }
    }

    /// <summary>Field number for the "PID" field.</summary>
    public const int PIDFieldNumber = 2;
    private ulong pID_;
    /// <summary>
    /// 用户ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong PID {
      get { return pID_; }
      set {
        pID_ = value;
      }
    }

    /// <summary>Field number for the "AddCount" field.</summary>
    public const int AddCountFieldNumber = 11;
    private int addCount_;
    /// <summary>
    ///累计增加的数量 精英
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int AddCount {
      get { return addCount_; }
      set {
        addCount_ = value;
      }
    }

    /// <summary>Field number for the "RemainCount" field.</summary>
    public const int RemainCountFieldNumber = 12;
    private int remainCount_;
    /// <summary>
    ///剩余使用的数量 配置ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int RemainCount {
      get { return remainCount_; }
      set {
        remainCount_ = value;
      }
    }

    /// <summary>Field number for the "LastRefreshTime" field.</summary>
    public const int LastRefreshTimeFieldNumber = 13;
    private long lastRefreshTime_;
    /// <summary>
    ///上次刷新的时间
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long LastRefreshTime {
      get { return lastRefreshTime_; }
      set {
        lastRefreshTime_ = value;
      }
    }

    /// <summary>Field number for the "EndTime" field.</summary>
    public const int EndTimeFieldNumber = 14;
    private long endTime_;
    /// <summary>
    ///下次重置的时间
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long EndTime {
      get { return endTime_; }
      set {
        endTime_ = value;
      }
    }

    /// <summary>Field number for the "BaseId" field.</summary>
    public const int BaseIdFieldNumber = 15;
    private int baseId_;
    /// <summary>
    /// baseid
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int BaseId {
      get { return baseId_; }
      set {
        baseId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ComCountMD);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ComCountMD other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ID != other.ID) return false;
      if (PID != other.PID) return false;
      if (AddCount != other.AddCount) return false;
      if (RemainCount != other.RemainCount) return false;
      if (LastRefreshTime != other.LastRefreshTime) return false;
      if (EndTime != other.EndTime) return false;
      if (BaseId != other.BaseId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ID != 0UL) hash ^= ID.GetHashCode();
      if (PID != 0UL) hash ^= PID.GetHashCode();
      if (AddCount != 0) hash ^= AddCount.GetHashCode();
      if (RemainCount != 0) hash ^= RemainCount.GetHashCode();
      if (LastRefreshTime != 0L) hash ^= LastRefreshTime.GetHashCode();
      if (EndTime != 0L) hash ^= EndTime.GetHashCode();
      if (BaseId != 0) hash ^= BaseId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ID != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(ID);
      }
      if (PID != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(PID);
      }
      if (AddCount != 0) {
        output.WriteRawTag(88);
        output.WriteInt32(AddCount);
      }
      if (RemainCount != 0) {
        output.WriteRawTag(96);
        output.WriteInt32(RemainCount);
      }
      if (LastRefreshTime != 0L) {
        output.WriteRawTag(104);
        output.WriteInt64(LastRefreshTime);
      }
      if (EndTime != 0L) {
        output.WriteRawTag(112);
        output.WriteInt64(EndTime);
      }
      if (BaseId != 0) {
        output.WriteRawTag(120);
        output.WriteInt32(BaseId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ID != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(ID);
      }
      if (PID != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(PID);
      }
      if (AddCount != 0) {
        output.WriteRawTag(88);
        output.WriteInt32(AddCount);
      }
      if (RemainCount != 0) {
        output.WriteRawTag(96);
        output.WriteInt32(RemainCount);
      }
      if (LastRefreshTime != 0L) {
        output.WriteRawTag(104);
        output.WriteInt64(LastRefreshTime);
      }
      if (EndTime != 0L) {
        output.WriteRawTag(112);
        output.WriteInt64(EndTime);
      }
      if (BaseId != 0) {
        output.WriteRawTag(120);
        output.WriteInt32(BaseId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ID != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(ID);
      }
      if (PID != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(PID);
      }
      if (AddCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(AddCount);
      }
      if (RemainCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(RemainCount);
      }
      if (LastRefreshTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(LastRefreshTime);
      }
      if (EndTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(EndTime);
      }
      if (BaseId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(BaseId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ComCountMD other) {
      if (other == null) {
        return;
      }
      if (other.ID != 0UL) {
        ID = other.ID;
      }
      if (other.PID != 0UL) {
        PID = other.PID;
      }
      if (other.AddCount != 0) {
        AddCount = other.AddCount;
      }
      if (other.RemainCount != 0) {
        RemainCount = other.RemainCount;
      }
      if (other.LastRefreshTime != 0L) {
        LastRefreshTime = other.LastRefreshTime;
      }
      if (other.EndTime != 0L) {
        EndTime = other.EndTime;
      }
      if (other.BaseId != 0) {
        BaseId = other.BaseId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ID = input.ReadUInt64();
            break;
          }
          case 16: {
            PID = input.ReadUInt64();
            break;
          }
          case 88: {
            AddCount = input.ReadInt32();
            break;
          }
          case 96: {
            RemainCount = input.ReadInt32();
            break;
          }
          case 104: {
            LastRefreshTime = input.ReadInt64();
            break;
          }
          case 112: {
            EndTime = input.ReadInt64();
            break;
          }
          case 120: {
            BaseId = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ID = input.ReadUInt64();
            break;
          }
          case 16: {
            PID = input.ReadUInt64();
            break;
          }
          case 88: {
            AddCount = input.ReadInt32();
            break;
          }
          case 96: {
            RemainCount = input.ReadInt32();
            break;
          }
          case 104: {
            LastRefreshTime = input.ReadInt64();
            break;
          }
          case 112: {
            EndTime = input.ReadInt64();
            break;
          }
          case 120: {
            BaseId = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// 数据结构 Field 枚举
  ///---------------------------------------------------------------
  /// 消息 可以根据消息实际需要拆开；按一些分类消息比较多的时候，可以单独分个段出来；
  /// StartId=5620
  /// </summary>
  public sealed partial class UpComCountInfoSrv : pb::IMessage<UpComCountInfoSrv>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<UpComCountInfoSrv> _parser = new pb::MessageParser<UpComCountInfoSrv>(() => new UpComCountInfoSrv());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<UpComCountInfoSrv> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ProtoMsg.ComcountReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpComCountInfoSrv() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpComCountInfoSrv(UpComCountInfoSrv other) : this() {
      baseId_ = other.baseId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpComCountInfoSrv Clone() {
      return new UpComCountInfoSrv(this);
    }

    /// <summary>Field number for the "BaseId" field.</summary>
    public const int BaseIdFieldNumber = 1;
    private int baseId_;
    /// <summary>
    ///> 通用次数id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int BaseId {
      get { return baseId_; }
      set {
        baseId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as UpComCountInfoSrv);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(UpComCountInfoSrv other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (BaseId != other.BaseId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (BaseId != 0) hash ^= BaseId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (BaseId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(BaseId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (BaseId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(BaseId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (BaseId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(BaseId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(UpComCountInfoSrv other) {
      if (other == null) {
        return;
      }
      if (other.BaseId != 0) {
        BaseId = other.BaseId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            BaseId = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            BaseId = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
