// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: fight.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ProtoMsg {

  /// <summary>Holder for reflection information generated from fight.proto</summary>
  public static partial class FightReflection {

    #region Descriptor
    /// <summary>File descriptor for fight.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static FightReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgtmaWdodC5wcm90bxIIcHJvdG9Nc2caCmJhc2UucHJvdG8aCmdvZ28ucHJv",
            "dG8irwUKB0ZpZ2h0TUQSLQoDUElEGAEgASgEQiDy3h8cZ29ybToicHJpbWFy",
            "eWtleTtjb2x1bW46cGlkIhIkCgRSb2xlGAsgASgDQhby3h8SZ29ybToiY29s",
            "dW1uOnJvbGUiEiYKBVNraWxsGAwgASgDQhfy3h8TZ29ybToiY29sdW1uOnNr",
            "aWxsIhImCgVFcXVpcBgNIAEoA0IX8t4fE2dvcm06ImNvbHVtbjplcXVpcCIS",
            "KgoHUGFydG5lchgOIAEoA0IZ8t4fFWdvcm06ImNvbHVtbjpwYXJ0bmVyIhIq",
            "CgdFeHBsb3JlGA8gASgDQhny3h8VZ29ybToiY29sdW1uOmV4cGxvcmUiEiIK",
            "A0FsbBgQIAEoA0IV8t4fEWdvcm06ImNvbHVtbjphbGwiEjAKCkhpc3RvcnlN",
            "YXgYESABKANCHPLeHxhnb3JtOiJjb2x1bW46aGlzdG9yeW1heCISMgoLSGlz",
            "dG9yeVJvbGUYEiABKANCHfLeHxlnb3JtOiJjb2x1bW46aGlzdG9yeXJvbGUi",
            "EjQKDEhpc3RvcnlTa2lsbBgTIAEoA0Ie8t4fGmdvcm06ImNvbHVtbjpoaXN0",
            "b3J5c2tpbGwiEjQKDEhpc3RvcnlFcXVpcBgUIAEoA0Ie8t4fGmdvcm06ImNv",
            "bHVtbjpoaXN0b3J5ZXF1aXAiEjgKDkhpc3RvcnlQYXJ0bmVyGBUgASgDQiDy",
            "3h8cZ29ybToiY29sdW1uOmhpc3RvcnlwYXJ0bmVyIhJcCgpSZXdhcmRMaXN0",
            "GB4gASgLMhwucHJvdG9Nc2cuSTMyV2l0aEJvb2xNYXBEYXRhQiry3h8iZ29y",
            "bToidHlwZTpibG9iO2NvbHVtbjpyZXdhcmRsaXN0IsjeHwA6GcqiHwVmaWdo",
            "dPCiHwDQoh8B4KIfAdqiHwAiEwoRR2V0RmlnaHRSZXdhcmRSZXEiEwoRR2V0",
            "RmlnaHRSZXdhcmRSZXQiUQoWVGVhbU1hdGVQb3dlclVwZGF0ZU50ZhIOCgZU",
            "ZWFtSUQYASABKAQSCwoDUElEGAIgASgEEgsKA0VJRBgDIAEoBBINCgVQb3dl",
            "chgEIAEoA0IEyOMeAWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::ProtoMsg.BaseReflection.Descriptor, global::Gogoproto.GogoReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::ProtoMsg.FightMD), global::ProtoMsg.FightMD.Parser, new[]{ "PID", "Role", "Skill", "Equip", "Partner", "Explore", "All", "HistoryMax", "HistoryRole", "HistorySkill", "HistoryEquip", "HistoryPartner", "RewardList" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ProtoMsg.GetFightRewardReq), global::ProtoMsg.GetFightRewardReq.Parser, null, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ProtoMsg.GetFightRewardRet), global::ProtoMsg.GetFightRewardRet.Parser, null, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ProtoMsg.TeamMatePowerUpdateNtf), global::ProtoMsg.TeamMatePowerUpdateNtf.Parser, new[]{ "TeamID", "PID", "EID", "Power" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  ///战力数据表
  /// </summary>
  public sealed partial class FightMD : pb::IMessage<FightMD>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<FightMD> _parser = new pb::MessageParser<FightMD>(() => new FightMD());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<FightMD> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ProtoMsg.FightReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FightMD() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FightMD(FightMD other) : this() {
      pID_ = other.pID_;
      role_ = other.role_;
      skill_ = other.skill_;
      equip_ = other.equip_;
      partner_ = other.partner_;
      explore_ = other.explore_;
      all_ = other.all_;
      historyMax_ = other.historyMax_;
      historyRole_ = other.historyRole_;
      historySkill_ = other.historySkill_;
      historyEquip_ = other.historyEquip_;
      historyPartner_ = other.historyPartner_;
      rewardList_ = other.rewardList_ != null ? other.rewardList_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FightMD Clone() {
      return new FightMD(this);
    }

    /// <summary>Field number for the "PID" field.</summary>
    public const int PIDFieldNumber = 1;
    private ulong pID_;
    /// <summary>
    /// 用户ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong PID {
      get { return pID_; }
      set {
        pID_ = value;
      }
    }

    /// <summary>Field number for the "Role" field.</summary>
    public const int RoleFieldNumber = 11;
    private long role_;
    /// <summary>
    /// 角色部分-战力
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Role {
      get { return role_; }
      set {
        role_ = value;
      }
    }

    /// <summary>Field number for the "Skill" field.</summary>
    public const int SkillFieldNumber = 12;
    private long skill_;
    /// <summary>
    /// 技能部分-战力
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Skill {
      get { return skill_; }
      set {
        skill_ = value;
      }
    }

    /// <summary>Field number for the "Equip" field.</summary>
    public const int EquipFieldNumber = 13;
    private long equip_;
    /// <summary>
    /// 装备部分-战力
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Equip {
      get { return equip_; }
      set {
        equip_ = value;
      }
    }

    /// <summary>Field number for the "Partner" field.</summary>
    public const int PartnerFieldNumber = 14;
    private long partner_;
    /// <summary>
    /// 伙伴部分-战力
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Partner {
      get { return partner_; }
      set {
        partner_ = value;
      }
    }

    /// <summary>Field number for the "Explore" field.</summary>
    public const int ExploreFieldNumber = 15;
    private long explore_;
    /// <summary>
    /// 探索部分-战力
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Explore {
      get { return explore_; }
      set {
        explore_ = value;
      }
    }

    /// <summary>Field number for the "All" field.</summary>
    public const int AllFieldNumber = 16;
    private long all_;
    /// <summary>
    /// 总战力
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long All {
      get { return all_; }
      set {
        all_ = value;
      }
    }

    /// <summary>Field number for the "HistoryMax" field.</summary>
    public const int HistoryMaxFieldNumber = 17;
    private long historyMax_;
    /// <summary>
    /// 历史最大总战力
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long HistoryMax {
      get { return historyMax_; }
      set {
        historyMax_ = value;
      }
    }

    /// <summary>Field number for the "HistoryRole" field.</summary>
    public const int HistoryRoleFieldNumber = 18;
    private long historyRole_;
    /// <summary>
    /// 历史最大角色战力
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long HistoryRole {
      get { return historyRole_; }
      set {
        historyRole_ = value;
      }
    }

    /// <summary>Field number for the "HistorySkill" field.</summary>
    public const int HistorySkillFieldNumber = 19;
    private long historySkill_;
    /// <summary>
    /// 历史最大技能战力
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long HistorySkill {
      get { return historySkill_; }
      set {
        historySkill_ = value;
      }
    }

    /// <summary>Field number for the "HistoryEquip" field.</summary>
    public const int HistoryEquipFieldNumber = 20;
    private long historyEquip_;
    /// <summary>
    /// 历史最大装备战力
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long HistoryEquip {
      get { return historyEquip_; }
      set {
        historyEquip_ = value;
      }
    }

    /// <summary>Field number for the "HistoryPartner" field.</summary>
    public const int HistoryPartnerFieldNumber = 21;
    private long historyPartner_;
    /// <summary>
    /// 历史最大伙伴战力
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long HistoryPartner {
      get { return historyPartner_; }
      set {
        historyPartner_ = value;
      }
    }

    /// <summary>Field number for the "RewardList" field.</summary>
    public const int RewardListFieldNumber = 30;
    private global::ProtoMsg.I32WithBoolMapData rewardList_;
    /// <summary>
    /// 战力已领取奖励
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ProtoMsg.I32WithBoolMapData RewardList {
      get { return rewardList_; }
      set {
        rewardList_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as FightMD);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(FightMD other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PID != other.PID) return false;
      if (Role != other.Role) return false;
      if (Skill != other.Skill) return false;
      if (Equip != other.Equip) return false;
      if (Partner != other.Partner) return false;
      if (Explore != other.Explore) return false;
      if (All != other.All) return false;
      if (HistoryMax != other.HistoryMax) return false;
      if (HistoryRole != other.HistoryRole) return false;
      if (HistorySkill != other.HistorySkill) return false;
      if (HistoryEquip != other.HistoryEquip) return false;
      if (HistoryPartner != other.HistoryPartner) return false;
      if (!object.Equals(RewardList, other.RewardList)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (PID != 0UL) hash ^= PID.GetHashCode();
      if (Role != 0L) hash ^= Role.GetHashCode();
      if (Skill != 0L) hash ^= Skill.GetHashCode();
      if (Equip != 0L) hash ^= Equip.GetHashCode();
      if (Partner != 0L) hash ^= Partner.GetHashCode();
      if (Explore != 0L) hash ^= Explore.GetHashCode();
      if (All != 0L) hash ^= All.GetHashCode();
      if (HistoryMax != 0L) hash ^= HistoryMax.GetHashCode();
      if (HistoryRole != 0L) hash ^= HistoryRole.GetHashCode();
      if (HistorySkill != 0L) hash ^= HistorySkill.GetHashCode();
      if (HistoryEquip != 0L) hash ^= HistoryEquip.GetHashCode();
      if (HistoryPartner != 0L) hash ^= HistoryPartner.GetHashCode();
      if (rewardList_ != null) hash ^= RewardList.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (PID != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(PID);
      }
      if (Role != 0L) {
        output.WriteRawTag(88);
        output.WriteInt64(Role);
      }
      if (Skill != 0L) {
        output.WriteRawTag(96);
        output.WriteInt64(Skill);
      }
      if (Equip != 0L) {
        output.WriteRawTag(104);
        output.WriteInt64(Equip);
      }
      if (Partner != 0L) {
        output.WriteRawTag(112);
        output.WriteInt64(Partner);
      }
      if (Explore != 0L) {
        output.WriteRawTag(120);
        output.WriteInt64(Explore);
      }
      if (All != 0L) {
        output.WriteRawTag(128, 1);
        output.WriteInt64(All);
      }
      if (HistoryMax != 0L) {
        output.WriteRawTag(136, 1);
        output.WriteInt64(HistoryMax);
      }
      if (HistoryRole != 0L) {
        output.WriteRawTag(144, 1);
        output.WriteInt64(HistoryRole);
      }
      if (HistorySkill != 0L) {
        output.WriteRawTag(152, 1);
        output.WriteInt64(HistorySkill);
      }
      if (HistoryEquip != 0L) {
        output.WriteRawTag(160, 1);
        output.WriteInt64(HistoryEquip);
      }
      if (HistoryPartner != 0L) {
        output.WriteRawTag(168, 1);
        output.WriteInt64(HistoryPartner);
      }
      if (rewardList_ != null) {
        output.WriteRawTag(242, 1);
        output.WriteMessage(RewardList);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (PID != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(PID);
      }
      if (Role != 0L) {
        output.WriteRawTag(88);
        output.WriteInt64(Role);
      }
      if (Skill != 0L) {
        output.WriteRawTag(96);
        output.WriteInt64(Skill);
      }
      if (Equip != 0L) {
        output.WriteRawTag(104);
        output.WriteInt64(Equip);
      }
      if (Partner != 0L) {
        output.WriteRawTag(112);
        output.WriteInt64(Partner);
      }
      if (Explore != 0L) {
        output.WriteRawTag(120);
        output.WriteInt64(Explore);
      }
      if (All != 0L) {
        output.WriteRawTag(128, 1);
        output.WriteInt64(All);
      }
      if (HistoryMax != 0L) {
        output.WriteRawTag(136, 1);
        output.WriteInt64(HistoryMax);
      }
      if (HistoryRole != 0L) {
        output.WriteRawTag(144, 1);
        output.WriteInt64(HistoryRole);
      }
      if (HistorySkill != 0L) {
        output.WriteRawTag(152, 1);
        output.WriteInt64(HistorySkill);
      }
      if (HistoryEquip != 0L) {
        output.WriteRawTag(160, 1);
        output.WriteInt64(HistoryEquip);
      }
      if (HistoryPartner != 0L) {
        output.WriteRawTag(168, 1);
        output.WriteInt64(HistoryPartner);
      }
      if (rewardList_ != null) {
        output.WriteRawTag(242, 1);
        output.WriteMessage(RewardList);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (PID != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(PID);
      }
      if (Role != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Role);
      }
      if (Skill != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Skill);
      }
      if (Equip != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Equip);
      }
      if (Partner != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Partner);
      }
      if (Explore != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Explore);
      }
      if (All != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(All);
      }
      if (HistoryMax != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(HistoryMax);
      }
      if (HistoryRole != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(HistoryRole);
      }
      if (HistorySkill != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(HistorySkill);
      }
      if (HistoryEquip != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(HistoryEquip);
      }
      if (HistoryPartner != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(HistoryPartner);
      }
      if (rewardList_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(RewardList);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(FightMD other) {
      if (other == null) {
        return;
      }
      if (other.PID != 0UL) {
        PID = other.PID;
      }
      if (other.Role != 0L) {
        Role = other.Role;
      }
      if (other.Skill != 0L) {
        Skill = other.Skill;
      }
      if (other.Equip != 0L) {
        Equip = other.Equip;
      }
      if (other.Partner != 0L) {
        Partner = other.Partner;
      }
      if (other.Explore != 0L) {
        Explore = other.Explore;
      }
      if (other.All != 0L) {
        All = other.All;
      }
      if (other.HistoryMax != 0L) {
        HistoryMax = other.HistoryMax;
      }
      if (other.HistoryRole != 0L) {
        HistoryRole = other.HistoryRole;
      }
      if (other.HistorySkill != 0L) {
        HistorySkill = other.HistorySkill;
      }
      if (other.HistoryEquip != 0L) {
        HistoryEquip = other.HistoryEquip;
      }
      if (other.HistoryPartner != 0L) {
        HistoryPartner = other.HistoryPartner;
      }
      if (other.rewardList_ != null) {
        if (rewardList_ == null) {
          RewardList = new global::ProtoMsg.I32WithBoolMapData();
        }
        RewardList.MergeFrom(other.RewardList);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            PID = input.ReadUInt64();
            break;
          }
          case 88: {
            Role = input.ReadInt64();
            break;
          }
          case 96: {
            Skill = input.ReadInt64();
            break;
          }
          case 104: {
            Equip = input.ReadInt64();
            break;
          }
          case 112: {
            Partner = input.ReadInt64();
            break;
          }
          case 120: {
            Explore = input.ReadInt64();
            break;
          }
          case 128: {
            All = input.ReadInt64();
            break;
          }
          case 136: {
            HistoryMax = input.ReadInt64();
            break;
          }
          case 144: {
            HistoryRole = input.ReadInt64();
            break;
          }
          case 152: {
            HistorySkill = input.ReadInt64();
            break;
          }
          case 160: {
            HistoryEquip = input.ReadInt64();
            break;
          }
          case 168: {
            HistoryPartner = input.ReadInt64();
            break;
          }
          case 242: {
            if (rewardList_ == null) {
              RewardList = new global::ProtoMsg.I32WithBoolMapData();
            }
            input.ReadMessage(RewardList);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            PID = input.ReadUInt64();
            break;
          }
          case 88: {
            Role = input.ReadInt64();
            break;
          }
          case 96: {
            Skill = input.ReadInt64();
            break;
          }
          case 104: {
            Equip = input.ReadInt64();
            break;
          }
          case 112: {
            Partner = input.ReadInt64();
            break;
          }
          case 120: {
            Explore = input.ReadInt64();
            break;
          }
          case 128: {
            All = input.ReadInt64();
            break;
          }
          case 136: {
            HistoryMax = input.ReadInt64();
            break;
          }
          case 144: {
            HistoryRole = input.ReadInt64();
            break;
          }
          case 152: {
            HistorySkill = input.ReadInt64();
            break;
          }
          case 160: {
            HistoryEquip = input.ReadInt64();
            break;
          }
          case 168: {
            HistoryPartner = input.ReadInt64();
            break;
          }
          case 242: {
            if (rewardList_ == null) {
              RewardList = new global::ProtoMsg.I32WithBoolMapData();
            }
            input.ReadMessage(RewardList);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// 请求领取战力段奖励
  /// </summary>
  public sealed partial class GetFightRewardReq : pb::IMessage<GetFightRewardReq>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GetFightRewardReq> _parser = new pb::MessageParser<GetFightRewardReq>(() => new GetFightRewardReq());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GetFightRewardReq> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ProtoMsg.FightReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetFightRewardReq() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetFightRewardReq(GetFightRewardReq other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetFightRewardReq Clone() {
      return new GetFightRewardReq(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GetFightRewardReq);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GetFightRewardReq other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GetFightRewardReq other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
        }
      }
    }
    #endif

  }

  /// <summary>
  /// 请求领取战力段奖励 返回
  /// </summary>
  public sealed partial class GetFightRewardRet : pb::IMessage<GetFightRewardRet>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GetFightRewardRet> _parser = new pb::MessageParser<GetFightRewardRet>(() => new GetFightRewardRet());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GetFightRewardRet> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ProtoMsg.FightReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetFightRewardRet() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetFightRewardRet(GetFightRewardRet other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetFightRewardRet Clone() {
      return new GetFightRewardRet(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GetFightRewardRet);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GetFightRewardRet other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GetFightRewardRet other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
        }
      }
    }
    #endif

  }

  /// <summary>
  /// 组队成员 战力变化通知
  /// </summary>
  public sealed partial class TeamMatePowerUpdateNtf : pb::IMessage<TeamMatePowerUpdateNtf>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TeamMatePowerUpdateNtf> _parser = new pb::MessageParser<TeamMatePowerUpdateNtf>(() => new TeamMatePowerUpdateNtf());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TeamMatePowerUpdateNtf> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ProtoMsg.FightReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TeamMatePowerUpdateNtf() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TeamMatePowerUpdateNtf(TeamMatePowerUpdateNtf other) : this() {
      teamID_ = other.teamID_;
      pID_ = other.pID_;
      eID_ = other.eID_;
      power_ = other.power_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TeamMatePowerUpdateNtf Clone() {
      return new TeamMatePowerUpdateNtf(this);
    }

    /// <summary>Field number for the "TeamID" field.</summary>
    public const int TeamIDFieldNumber = 1;
    private ulong teamID_;
    /// <summary>
    /// 队伍ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong TeamID {
      get { return teamID_; }
      set {
        teamID_ = value;
      }
    }

    /// <summary>Field number for the "PID" field.</summary>
    public const int PIDFieldNumber = 2;
    private ulong pID_;
    /// <summary>
    /// PID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong PID {
      get { return pID_; }
      set {
        pID_ = value;
      }
    }

    /// <summary>Field number for the "EID" field.</summary>
    public const int EIDFieldNumber = 3;
    private ulong eID_;
    /// <summary>
    /// EID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong EID {
      get { return eID_; }
      set {
        eID_ = value;
      }
    }

    /// <summary>Field number for the "Power" field.</summary>
    public const int PowerFieldNumber = 4;
    private long power_;
    /// <summary>
    /// Power
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Power {
      get { return power_; }
      set {
        power_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TeamMatePowerUpdateNtf);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TeamMatePowerUpdateNtf other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TeamID != other.TeamID) return false;
      if (PID != other.PID) return false;
      if (EID != other.EID) return false;
      if (Power != other.Power) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (TeamID != 0UL) hash ^= TeamID.GetHashCode();
      if (PID != 0UL) hash ^= PID.GetHashCode();
      if (EID != 0UL) hash ^= EID.GetHashCode();
      if (Power != 0L) hash ^= Power.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (TeamID != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(TeamID);
      }
      if (PID != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(PID);
      }
      if (EID != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(EID);
      }
      if (Power != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(Power);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (TeamID != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(TeamID);
      }
      if (PID != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(PID);
      }
      if (EID != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(EID);
      }
      if (Power != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(Power);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (TeamID != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(TeamID);
      }
      if (PID != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(PID);
      }
      if (EID != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(EID);
      }
      if (Power != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Power);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TeamMatePowerUpdateNtf other) {
      if (other == null) {
        return;
      }
      if (other.TeamID != 0UL) {
        TeamID = other.TeamID;
      }
      if (other.PID != 0UL) {
        PID = other.PID;
      }
      if (other.EID != 0UL) {
        EID = other.EID;
      }
      if (other.Power != 0L) {
        Power = other.Power;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            TeamID = input.ReadUInt64();
            break;
          }
          case 16: {
            PID = input.ReadUInt64();
            break;
          }
          case 24: {
            EID = input.ReadUInt64();
            break;
          }
          case 32: {
            Power = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            TeamID = input.ReadUInt64();
            break;
          }
          case 16: {
            PID = input.ReadUInt64();
            break;
          }
          case 24: {
            EID = input.ReadUInt64();
            break;
          }
          case 32: {
            Power = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
