GS_APPID=10200326
GS_APPKEY=c49CILCy2JXRX2Z36YUAb3R3gVsNRK29
GS_PlatformID=1
GS_Channel=310003
GS_Store_Channel=310003
GS_Sub_Channel=310003
GSSERVER_URL=https://gssdk-api.dobest.cn
yoka_app_id=10200326
yoka_is_online=true
yoka_qq_appid=false
yoka_wechat_appid=false
yoka_is_off_login_guest=true
yoka_is_off_login_qq=true
yoka_is_off_login_weixin=true
yoka_is_off_pay_weixin=false
yoka_is_off_pay_alipay=false
yoka_is_off_login_yoka=false
isNewLogin=false
GSSDK_ADMIN_SERVER_URL=https://sdk-admin-api.dobest.cn
